/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const JobApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'applicant' : IDL.Principal,
  'appliedAt' : Time,
  'jobId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CompanyProfile = IDL.Record({
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Text,
  'industry' : IDL.Text,
});
export const JobListing = IDL.Record({
  'id' : IDL.Text,
  'compensation' : IDL.Text,
  'title' : IDL.Text,
  'postedAt' : Time,
  'responsibilities' : IDL.Vec(IDL.Text),
  'jobType' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Principal,
  'category' : IDL.Text,
  'requirements' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const PaymentTransaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'user' : IDL.Principal,
  'currency' : IDL.Text,
  'timestamp' : Time,
  'paymentModel' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'portfolio' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'experience' : IDL.Text,
  'isCompany' : IDL.Bool,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'applyForJob' : IDL.Func([JobApplication], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCompanyProfile' : IDL.Func([CompanyProfile], [], []),
  'deleteJobListing' : IDL.Func([IDL.Text], [], []),
  'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getAllCompanyProfiles' : IDL.Func([], [IDL.Vec(CompanyProfile)], ['query']),
  'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentTransaction)], ['query']),
  'getCallerCompanyProfile' : IDL.Func(
      [],
      [IDL.Opt(CompanyProfile)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getCompanyProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CompanyProfile)],
      ['query'],
    ),
  'getJobApplications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobListing' : IDL.Func([IDL.Text], [IDL.Opt(JobListing)], ['query']),
  'getUserApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
  'getUserPayments' : IDL.Func([], [IDL.Vec(PaymentTransaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'postJobListing' : IDL.Func([JobListing], [], []),
  'processPayment' : IDL.Func([PaymentTransaction], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCompanyProfile' : IDL.Func([CompanyProfile], [], []),
  'updateJobListing' : IDL.Func([JobListing], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const JobApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'applicant' : IDL.Principal,
    'appliedAt' : Time,
    'jobId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CompanyProfile = IDL.Record({
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Text,
    'industry' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'id' : IDL.Text,
    'compensation' : IDL.Text,
    'title' : IDL.Text,
    'postedAt' : Time,
    'responsibilities' : IDL.Vec(IDL.Text),
    'jobType' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Principal,
    'category' : IDL.Text,
    'requirements' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const PaymentTransaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'user' : IDL.Principal,
    'currency' : IDL.Text,
    'timestamp' : Time,
    'paymentModel' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'portfolio' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'experience' : IDL.Text,
    'isCompany' : IDL.Bool,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'applyForJob' : IDL.Func([JobApplication], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCompanyProfile' : IDL.Func([CompanyProfile], [], []),
    'deleteJobListing' : IDL.Func([IDL.Text], [], []),
    'getAllApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getAllCompanyProfiles' : IDL.Func(
        [],
        [IDL.Vec(CompanyProfile)],
        ['query'],
      ),
    'getAllJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentTransaction)], ['query']),
    'getCallerCompanyProfile' : IDL.Func(
        [],
        [IDL.Opt(CompanyProfile)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getCompanyProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CompanyProfile)],
        ['query'],
      ),
    'getJobApplications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobListing' : IDL.Func([IDL.Text], [IDL.Opt(JobListing)], ['query']),
    'getUserApplications' : IDL.Func([], [IDL.Vec(JobApplication)], ['query']),
    'getUserPayments' : IDL.Func([], [IDL.Vec(PaymentTransaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'postJobListing' : IDL.Func([JobListing], [], []),
    'processPayment' : IDL.Func([PaymentTransaction], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateApplicationStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCompanyProfile' : IDL.Func([CompanyProfile], [], []),
    'updateJobListing' : IDL.Func([JobListing], [], []),
  });
};

export const init = ({ IDL }) => { return []; };