/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @dfinity/caffeine-bindgen@0.1.0-beta.7.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompanyProfile {
  'owner' : Principal,
  'name' : string,
  'description' : string,
  'location' : string,
  'industry' : string,
}
export interface JobApplication {
  'id' : string,
  'status' : string,
  'applicant' : Principal,
  'appliedAt' : Time,
  'jobId' : string,
}
export interface JobListing {
  'id' : string,
  'compensation' : string,
  'title' : string,
  'postedAt' : Time,
  'responsibilities' : Array<string>,
  'jobType' : string,
  'description' : string,
  'company' : Principal,
  'category' : string,
  'requirements' : Array<string>,
  'location' : string,
}
export interface PaymentTransaction {
  'id' : string,
  'status' : string,
  'user' : Principal,
  'currency' : string,
  'timestamp' : Time,
  'paymentModel' : string,
  'amount' : number,
}
export type Time = bigint;
export interface UserProfile {
  'portfolio' : Array<string>,
  'name' : string,
  'email' : string,
  'experience' : string,
  'isCompany' : boolean,
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'applyForJob' : ActorMethod<[JobApplication], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCompanyProfile' : ActorMethod<[CompanyProfile], undefined>,
  'deleteJobListing' : ActorMethod<[string], undefined>,
  'getAllApplications' : ActorMethod<[], Array<JobApplication>>,
  'getAllCompanyProfiles' : ActorMethod<[], Array<CompanyProfile>>,
  'getAllJobListings' : ActorMethod<[], Array<JobListing>>,
  'getAllPayments' : ActorMethod<[], Array<PaymentTransaction>>,
  'getCallerCompanyProfile' : ActorMethod<[], [] | [CompanyProfile]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyJobListings' : ActorMethod<[], Array<JobListing>>,
  'getCompanyProfile' : ActorMethod<[Principal], [] | [CompanyProfile]>,
  'getJobApplications' : ActorMethod<[string], Array<JobApplication>>,
  'getJobListing' : ActorMethod<[string], [] | [JobListing]>,
  'getUserApplications' : ActorMethod<[], Array<JobApplication>>,
  'getUserPayments' : ActorMethod<[], Array<PaymentTransaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'postJobListing' : ActorMethod<[JobListing], undefined>,
  'processPayment' : ActorMethod<[PaymentTransaction], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateApplicationStatus' : ActorMethod<[string, string], undefined>,
  'updateCompanyProfile' : ActorMethod<[CompanyProfile], undefined>,
  'updateJobListing' : ActorMethod<[JobListing], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];